### ISSUE TITLE
DESTROY-THREAD: soft thread destruction

### ISSUE THREAD

**Issue by phoe** [sionescu/bordeaux-threads#104]
https://github.com/sionescu/bordeaux-threads/blob/07a6999eb922498511af04ff74825bbe462fce8d/docs/content/threads/destroy-thread.md#L31-L32

I am sure that I am not the first person to come up with this idea, but would adding a `softp` keyword/optional argument to `destroy-thread` be a good idea? The idea does not involve implementation-specific functionality - it could be done via interrupting a thread with a `(throw 'bt::%soft-destroy-thread nil)`. A well-behaved thread would then unwind its stack in a normal CL way, and gracefully terminate.

A requirement for that to happen would be to wrap the thread code in `(catch 'bt::%soft-destroy-thread ...)` in order to establish a matching catch tag.

**Comment by sionescu** [comment]
As far as I can tell all CL runtimes implement their `destroy-thread` exactly as you've specified here, so it's not clear to me what we gain by doing this.
That comment is from before I took over the maintenance of B-T and I'm not sure it's correct, maybe I should just delete it.

**Comment by phoe** [comment]
Oh - then, if you are *sure* that is the case, then all implementations actually perform proper stack unwinding, and this comment does no longer apply.

As for being a little bit more than sure, I assume that this behavior could even be tested inside BT itself.

```lisp
(defvar *test* nil)

(defun thread-fn ()
  (setf *test* :entered)
  (unwind-protect (progn (sleep 5) (setf *test* :failed))
    (unless (eq *test* :failed)
      (setf *test* :success))))

(defun test ()
  (let ((thread (make-thread #'thread-fn)))
    (sleep 1)
    (destroy-thread thread)
    (join-thread thread)
    (assert (eq *test* :success))))
```

Similar scenarios can be devised with locks, both in and out of `unwind-protect` cleanup forms.

Do you know whether there is anything like that in the BT test suite?

**Comment by sionescu** [comment]
I'll add it to the test suite. You're right that thread termination needs more tests.

**Comment by sionescu** [comment]
I turns out that ABCL doesn't execute cleanup forms, so I filed https://github.com/armedbear/abcl/issues/430.

**Comment by phoe** [comment]
Good finding! Any other implementations in {SBCL, CCL, ECL, Clasp, CLISP, LW, ACL, Mezzano} that you are aware do not unwind?

**Comment by sionescu** [comment]
The other 4 that are being tested pass the test: https://app.travis-ci.com/github/sionescu/bordeaux-threads. I don't know about Clasp, LW, ACL or Mezzano.

**Comment by phoe** [comment]
A report from `#clasp` on Libera Chat states that Clasp properly unwinds the thread.

```lisp
08:55 < phoe> could I get someone with a running Clasp to tell me a little bit about 
              https://github.com/sionescu/bordeaux-threads/issues/104 ?
08:56 < phoe> in particular, does destroying a thread in Clasp unwind it
13:25 < kpoeck> phoe, running the test from 
                https://github.com/sionescu/bordeaux-threads/issues/104 works, t.m. the 
                assertion holds and *test* has the value :success
13:27 < phoe> kpoeck: thanks!
```
