### ISSUE TITLE
Suggestion: make-thread should defult name to something

### ISSUE THREAD

**Issue by Yehouda** [sionescu/bordeaux-threads#106]
It is is better if make-thread default the name of a thread to something, e.g. to
 `(format nil "Unknown treads ~d" (incf *unknown-threads-count*))`.

**Comment by sionescu** [comment]
I'm curious, what problem is this causing ?
And, is this true for other primitives as well, such as locks or condition variables  ?

**Comment by Yehouda** [comment]
It is not causing a problem, but adding the name make it easier to debug.

The problem is when you list the processes and you see 14 threads called NIL, one of them is doing X, and a moment later one of them is doing Y. Is it the same thread or not? 

Naming other primitives is also useful, mainly because they appear in errors and backtraces. But you normally don't list them, so "anonymous" names that are useful only to distinguish between them are much less useful.  You really want to nudge the user to give a descriptive name.

**Comment by sionescu** [comment]
I implemented this in f8087219ab3d. Thanks !
