### ISSUE TITLE
apiv2's make-thread failed in ccl

### ISSUE THREAD

**Issue by hxzrx** [sionescu/bordeaux-threads#108]
The %semaphore slot in the thread class is initialize by (%make-semaphore nil 0), 
which calls (ccl:make-semaphore :count count),
but ccl:make-semaphore accept null parameter.

So, when ```(bt2:make-thread #'(lambda () t))``` was made in repl, 
a condition signaled then:
Too many arguments in call to #<Compiled-function CCL:MAKE-SEMAPHORE #x30000008964F>:                                                
2 arguments provided, at most 0 accepted.
...

My ccl version is 1.12 LinuxX8664.

And this is the ccl's make-semaphore src:
```
(defun make-semaphore ()
  "Create and return a semaphore, which can be used for synchronization
between threads."
  (%istruct 'semaphore (%make-semaphore-ptr)))
```

**Comment by sionescu** [comment]
You need at least CCL release 1.12.1.

**Comment by hxzrx** [comment]
> You need at least CCL release 1.12.1.

Yes, 1.12.1 works. Thank you!
