### ISSUE TITLE
How are users supposed to find about the package "BORDEAUX-THREADS-2"?

### ISSUE THREAD

**Issue by Yehouda** [sionescu/bordeaux-threads#116]
There is no mention of the package in the documentation, so existing users are unlikely to realize that they need to change the package that they use to use the uptodate version. 

Assuming users should use apiv2, this should be made clear.

Even better would be to warn the user that they use an out-of-date interface when they use apiv1, because most of existing users probably are not going to bother to read the manual again, but it is not obvious where that should be done.

**Comment by sionescu** [comment]
> There is no mention of the package in the documentation, so existing users are unlikely to realize that they need to change the package that they use to use the uptodate version.
> Assuming users should use apiv2, this should be made clear.

Thanks for noticing this, I will add a mention in the documentation.

> Even better would be to warn the user that they use an out-of-date interface when they use apiv1, because most of existing users probably are not going to bother to read the manual again, but it is not obvious where that should be done.

I'll look into that. Adding a deprecation notice for `BT:MAKE-THREAD` and `BT:MAKE-LOCK` should suffice.

**Comment by sionescu** [comment]
Done.
