### ISSUE TITLE
Apiv1 now uses the broken "impl-lispworks-condition-variables" uncodnitionally.

### ISSUE THREAD

**Issue by Yehouda** [sionescu/bordeaux-threads#117]
The apiv1 system now includes the broken  "impl-lispworks-condition-variables" uncoonditionally, while it used to include it only for version 4 and 5. priot to this change
https://github.com/sionescu/bordeaux-threads/commit/39d6790d24002df43e24b3c2d6f41524839b74d5

So now apiv1 is broken on Lispwokrs.

Since users are unlikely yo figure out that they need to chang ethe package to use the uptodate version (apiv2) (see issue 116), that means that now Bordeaux is broken for most existing users.

**Comment by sionescu** [comment]
For better or for worse, I believe there are few people using Bordeaux-Threads on Lispworks, otherwise I would have received a report long ago, and since I don't have a LW licence, I can't test manually.

I'll see if I can fix this when I'm back from vacation, in a couple of weeks.

**Comment by Yehouda** [comment]
Users that want stability tend to download new versions infrequently, so it will take time to hit them

You can use the [personal edition](http://www.lispworks.com/downloads/index.html) for testing.

It would be useful to add at the top of the broken file a form that checks, something like:
```
#-(or lispworks4 lispworks4) (error ...
```

So even if the asd file gets broken again the file will not load. At the moment it just causes hanging, and it i snot that easy to debug it. 

I don't actually know if there are still users that use LispWorks5 or earlier, so maybe just get rid of it completely.

**Comment by tdrhq** [comment]
@sionescu Definitely using a Bordeaux threads with Lispworks, and definitely hit this bug with a Quicklisp update. (I hadn't updated my quicklisp in a while, so it took a while for me to catch the breakage)

**Comment by tdrhq** [comment]
@Yehouda if you need a fix, you can use `quick-patch` to get the version from my PR.

**Comment by sionescu** [comment]
Fixed.
