### ISSUE TITLE
Latest release breaks lparallel

### ISSUE THREAD

**Issue by quicklisp** [sionescu/bordeaux-threads#121]
Hi, the deprecation full warning in the new release breaks `lparallel`, which in turn breaks a lot of other stuff. Are you willing to remove the warning? Do you know what must be done to fix lparallel?

http://report.quicklisp.org/2023-09-18/failure-report.html#lparallel

**Comment by sionescu** [comment]
I'll remove the warning and make another release today, then work with lparallel to switch to the new API.
Do you know of a an easy (ready-made) way to mark a function a deprecated, e.g. by issuing a compile-time style warning ?

**Comment by quicklisp** [comment]
Sorry, I don’t know if a portable approach. Sbcl has some internal tools for it. On Sep 19, 2023, at 13:31, Stelian Ionescu ***@***.***> wrote:﻿
I'll remove the warning and make another release today, then work with lparallel to switch to the new API.
Do you know of a an easy (ready-made) way to mark a function a deprecated, e.g. by issuing a compile-time style warning ?

**Comment by sionescu** [comment]
Published release 0.9.3.
