### ISSUE TITLE
Update to bt2 with dependency using v1

### ISSUE THREAD

**Issue by kilianmh** [sionescu/bordeaux-threads#124]
When trying to update a library to bt2 which depends on a library that uses v1 the following problem arises (sbcl 2.4.4):

```common-lisp
(bt2:thread-alive-p (bt:make-thread (lambda ())))
;; => no applicable method error

(bt2:destroy-thread (bt:make-thread (lambda ())))
;; => no applicable method error
```

Are these errors intended behaviour or should these cases be supported for gradual migration?

**Comment by sionescu** [comment]
Yes, they are the intended behaviour. Live migration is not supported.
