### ISSUE TITLE
Unbound variable bt2:*supports-threads-p*

### ISSUE THREAD

**Issue by kilianmh** [sionescu/bordeaux-threads#125]
After loading `bordeaux-threads` on sbcl 2.4.5, ccl 1.12.2:

```common-lisp
bt:*supports-threads-p*
;; -> T
```

```common-lisp
bt2:*supports-threads-p*
;; Debugger entered on #<UNBOUND-VARIABLE *SUPPORTS-THREADS-P*
```

**Comment by sionescu** [comment]
What for ?

**Comment by kilianmh** [comment]
I thought since `*supports-threads-p*` is exported from package :bt2 https://github.com/sionescu/bordeaux-threads/blob/50ade2908082a1305a4e3ef4a4363aacda653f94/apiv2/pkgdcl.lisp#L13 Or since version 2 does not support non-threaded implementations, the exported symbol should be removed?

**Comment by kilianmh** [comment]
Now i found the cause why `*supports-threads-p*` is unbound.

In `apiv2/bordeaux-threads.lisp` `+supports-threads-p+` is defined as constant with surrounding `+`:

https://github.com/sionescu/bordeaux-threads/blob/50ade2908082a1305a4e3ef4a4363aacda653f94/apiv2/bordeaux-threads.lisp#L6-L9

and in `apiv2/pkgdcl.lisp` `*supports-threads-p*`is exported  with surrounding `*`:

https://github.com/sionescu/bordeaux-threads/blob/50ade2908082a1305a4e3ef4a4363aacda653f94/apiv2/pkgdcl.lisp#L13

**Comment by sionescu** [comment]
Fixed, thank you.
