### ISSUE TITLE
Lispworks problem

### ISSUE THREAD

**Issue by gzacharias** [sionescu/bordeaux-threads#16]
Failing to quickload bordeaux-threads into lispworks.  Using latest quicklisp distribution and Lispworks 7.0. Error signalled is undefined function DEFINE-CONDITION-WAIT-COMPILER-MACRO, the underlying cause seems to be that impl-lispworks-condition-variables.lisp is missing an in-package form.

**Comment by aamedina** [comment]
I just ran into this myself. It looks like the quicklisp project for bordeaux-threads is out of date. The file in question should not be included on LispWorks 7.0. Cloning the latest git repository locally into your local-projects should supercede the remote version available from quicklisp, and any dependent systems should load successfully.

**Comment by sionescu** [comment]
Closing because the latest release made it into Quicklisp.
