### ISSUE TITLE
default-implementations lambda lists

### ISSUE THREAD

**Issue by dkochmanski** [sionescu/bordeaux-threads#25]
default-implementation operator lambda lists are not congruent in some cases with the particular implementations – for instance:

default-implementations.lisp:
`with-recursive-lock-held ((place &key timeout) &body body)`

sbcl-impl.lisp:
`with-recursive-lock-held ((place) &body body)`

While SBCL already has the timeout keyword in its inner implementation, this would be a reasonable fix to add the implementation, but the point is about the congruency, I think that it would be better to the same lambda-list and to declare (if not implemented for the particular implementation), that for instance `timeout` is ignored (maybe issue a warning too?).

I can create an appropriate pull request, I'm asking for feedback and if it will get accepted.

**Comment by sionescu** [comment]
Oops, I had forgotten about this. Sounds like a good idea if you can come up with a patch.

**Comment by dkochmanski** [comment]
split PR with semaphores and made fix for this a separate PR

**Comment by sionescu** [comment]
Take a look at the "apiv2" branch. It breaks the current API in several ways, but it's much cleaner.

**Comment by sionescu** [comment]
I merged the apiv2 branch, so I consider this solved.
