### ISSUE TITLE
Undocumented how to get return value of function given to make-thread

### ISSUE THREAD

**Issue by jimka2001** [sionescu/bordeaux-threads#26]
I asked the question on comp.lang.lisp https://groups.google.com/d/msg/comp.lang.lisp/4_avbEqQw0s/9Kbk_CD6DwAJ

The issue is that the documentation
 https://trac.common-lisp.net/bordeaux-threads/wiki/ApiDocumentation 
does not seem to specify whether join-thread returns the value of the function given to make-thread.
In fact the documentation does not indicate what the correct way to get the return value is without using global variables and locks.

I suspect this is simply an omission from the documentation, or that I'm reading the wrong documentation.

My suggested fix is to update the documentation, and also update the docstring(s) of join-thread.

**Comment by phoe** [comment]
Fixed by `286dd93`, but related to #53 since the documentation is not yet updated.

**Comment by sionescu** [comment]
Closing because I've updated the documentation.
