### ISSUE TITLE
Please provide a function to test whether a lock is held

### ISSUE THREAD

**Issue by phmarek** [sionescu/bordeaux-threads#27]
Eg. SBCL has `sb-thread:holding-mutex-p`, which makes developing via `ASSERT`s quite easier.

Please provide a similar function for the `B-T` locks... at least on the implementations that have something similar.

Thank you very much!

**Comment by sionescu** [comment]
Good idea, but I won't have time any time soon to take care of it especially because it requires installing/updating many implementations and reading their docs.

**Comment by lmj** [comment]
I didn't see anything in CCL that would allow us to write `bt:lock-held-p`. Also, code like `(when (bt:lock-held-p lock) ...)` is generally to be avoided because that's a race condition (the lock may or may not be held inside the `when` body).

**Comment by sionescu** [comment]
I agree. Closing.

**Comment by phmarek** [comment]
Well, the idea was to see whether the _current_ thread is holding the lock right now, ie. in an `assert`.

Yes, for other threads it would be racy, of course.
