### ISSUE TITLE
Make the (posix) thread-id available

### ISSUE THREAD

**Issue by phmarek** [sionescu/bordeaux-threads#28]
For logging purposes it would be very nice to have access to the (system-wide) thread-id.
Please provide a function for that, I guess defaulting on `(current-thread)` would be a good default.

Thank you very much!

**Comment by lmj** [comment]
A suitable thread id should be `(sxhash thread)`. If you really want the POSIX value, bordeaux-threads isn't getting in your way since `bt:thread` is already the implementation-specific thread type, for instance `sb-thread:thread` on SBCL.

**Comment by sionescu** [comment]
In practice, this needs the implementation to export such a function, otherwise we would be required to use the FFI and the differences in host implementation and OS would make that pretty difficult.
