### ISSUE TITLE
The function BORDEAUX-THREADS::AQUIRE-LOCK is undefined, SBCL

### ISSUE THREAD

**Issue by equwal** [sionescu/bordeaux-threads#32]
After doing  `(ql:quickload :bordeaux-threads)` and successfully loading bordeaux-threads, I  can use every function except for `aquire-lock` from the `:bordeaux-threads` package in the most recent iteration of SBCL. Even `with-lock-held` and `release-lock` work fine. Doing `(apropos :aquire-lock)` does return `AQUIRE-LOCK`, so it appears to be interned.

I am running on Debian stretch, if that matters. I would like to go test this on another system later.

**Comment by sionescu** [comment]
The function is ACQUIRE-LOCK, as you can easily see in the code.
