### ISSUE TITLE
Link to common-lisp.net project page in project description has a typo (very minor)

### ISSUE THREAD

**Issue by aplaice** [sionescu/bordeaux-threads#33]
In the repository description, the link to common-lisp.net has a typo.

To fix, would need to change:

https://common-lisp.net/projects/bordeaux-threads/ 

to 

https://common-lisp.net/project/bordeaux-threads/

(Sorry for being pedantic, but it's confusing when the URL looks like what you'd expect, but you get a 404.)

**Comment by sionescu** [comment]
Fixed, thanks.
