### ISSUE TITLE
How to check when a thread has finished?

### ISSUE THREAD

**Issue by sjl** [sionescu/bordeaux-threads#34]
I'm trying to find a way to take a thread object returned by `make-thread` and portably determine if it's still running.  The documentation for `thread-alive-p` says:

> Returns true if THREAD is alive, that is, if DESTROY-THREAD has not been called on it.

Testing on SBCL, however, shows that `thread-alive-p` will return `nil` once a thread has finished running normally, even if I've never called `destroy-thread` on it.  Is this just an oversight in the documentation, or is there some other way I should use to figure out if a thread has finished running (successfully or otherwise)?

**Comment by phoe** [comment]
Smells of a specification bug for me.

A thread that executes `(lambda () (print (+ 2 2)))` will not doing anything after it has successfully printed `4` to standard output. That thread is possibly already deallocated from the operating system and effectively "dead" - except not by means of `DESTROY-THREAD`, but by "natural causes" - it's done its job and died.

**Comment by sionescu** [comment]
@sjl: that's likely a documentation bug. I'll check the various implementations and clarify the docs.
@phoe: depending on how the CL host implements threads, if it uses POSIX pthreads creating joinable threads, then it may be that the thread stack does not get deallocated until the call to pthread_join(), which if delayed can lead to leaking the thread stack, which can be pretty large(in the megabyte range).

**Comment by phoe** [comment]
Related to #53.

**Comment by sionescu** [comment]
Closing because I've updated the documentation.
