### ISSUE TITLE
CONDITION-WAIT specification violated on SBCL

### ISSUE THREAD

**Issue by Shinmera** [sionescu/bordeaux-threads#35]
BT specifies:

> However and for whatever reason the thread is resumed, the system always reacquires LOCK before returning to the caller.

However, `bt:condition-wait` is implemented as a simple delegation to `sb-thread:condition-wait` which specifies:

> When neither a wakeup nor a re-acquisition occurs within the given time, returns NIL without re-acquiring MUTEX.

This means `bt:condition-wait` can return without the mutex being acquired in the current thread.

**Comment by scymtym** [comment]
Are you using a recent bt version? The ``condition-wait`` documentation string in the master version says

> … 
> If TIMEOUT is non-nil, the call will return after at most TIMEOUT
> seconds (approximately), whether or not a notification has occurred.
> Either NIL or T will be returned. A return of NIL indicates that the
> lock is no longer held and that the timeout has expired. A return of
> T indicates that the lock is held, in which case the timeout may or
> may not have expired.
> …

I didn't check, but may Quicklisp is lagging behind?

**Comment by Shinmera** [comment]
I was referring to the [Api Documentation document](https://trac.common-lisp.net/bordeaux-threads/wiki/ApiDocumentation#condition-waitcondition-variablelock), which desperately needs an update if it's as out of sync with the docstrings as it appears to be.

**Comment by phoe** [comment]
Related to #53.
