### ISSUE TITLE
Are threads futures? / Return value of JOIN-THREAD

### ISSUE THREAD

**Issue by phoe** [sionescu/bordeaux-threads#39]
I have noticed that `JOIN-THREAD` on my implementation (SBCL) returns the values of the function that was called inside the thread. This means that threads can effectively be used as a poor man's futures.

It allows me to do things like:

```lisp
(let ((thread (make-thread (lambda () (sleep 10) 42))))
  (join-thread thread))
;; => 42
```

I have observed that this is portable across SBCL, CCL, ECL and ABCL, and also possibly across other implementations, though this will need to be checked across all implementations supported by BT.

If it is checked, can this undefined feature be possibly turned into a defined feature in BT, by means of editing the documentation string of `JOIN-THREAD`?

**Comment by sionescu** [comment]
Done, thank you.
