### ISSUE TITLE
race condition in with-timeout macro

### ISSUE THREAD

**Issue by spaghettisalat** [sionescu/bordeaux-threads#41]
The following statement
```lisp
(when (thread-alive-p ,sleeper)
    (destroy-thread ,sleeper))
```
in the with-timeout macro is race-y, since the sleeper thread may already have finished execution after the call to thread-alive-p has returned, but before the call to destroy-thread is made. At least ECL (not sure about other implementations) also returns an error when attempting to destroy a thread, which has finished executing.

I'm not sure if the statement is needed at all, usually the sleeper thread should simply finish by itself. It it is needed, the call to destroy-thread needs to be wrapped in an ignore-errors form.

If you want to test this situation in ECL, please be aware, that we recently found a race condition which would make ECL fail with a segmentation fault in this exact scenario (see https://gitlab.com/embeddable-common-lisp/ecl/merge_requests/100).

**Comment by sionescu** [comment]
Indeed it makes little sense to do that. I removed the use of DESTROY-THREAD.
