### ISSUE TITLE
Please release 0.8.6

### ISSUE THREAD

**Issue by phoe** [sionescu/bordeaux-threads#46]
The BT version on Quicklisp (0.8.5) is old and does not have modern improvements, such as the `LOCK` type or function `LOCK-P`. I assume this is because Quicklisp pulls the newest release, which stays at 0.8.5 - I will clarify this with Quicklisp maintainers.

Nonetheless, I think that the improvements since 0.8.5 are worthy of a new release.

**Comment by sionescu** [comment]
I'll make a new release soon.

**Comment by phoe** [comment]
![28-days-later-logo svg](https://user-images.githubusercontent.com/15045546/41293350-50d5610c-6e55-11e8-8b33-0e839fca09bb.png)

I'd like to keep this issue alive.

**Comment by priyadarshan** [comment]
@phoe That is one of the funniest, gentle reminders I have seen. (I am also looking forward to release 0.8.6) Thank you.

**Comment by sionescu** [comment]
Thanks for the reminder. Done.
