### ISSUE TITLE
Sequential calls of with-timeout bug

### ISSUE THREAD

**Issue by riktam** [sionescu/bordeaux-threads#51]
Later sequential calls of with-timeout  may be interrupted by previous with-timeout calls.
Ex:
`CL-USER> (require :bordeaux-threads)
:BORDEAUX-THREADS
NIL
CL-USER> (defun x (y) (bt:with-timeout (5) (sleep y)))
X
CL-USER> (progn (x 4) (x 3))

A timeout set to 5 seconds occurred.
   [Condition of type BORDEAUX-THREADS:TIMEOUT]
`
where the (x 3) call was interrupted by the (x 4) call interrupting thread. 

This bug seems to have been created with the removal of the previous code that killed the interrupting thread. A possible fix without reverting to the previous code could be to give the timeout-tag a gensym per call, not per macro expansion. 

I was able to reproduce the bug on ccl 1.11.5 and abcl 1.5.0 on OSX.

**Comment by sionescu** [comment]
Fixed, thanks.
