### ISSUE TITLE
Documention Out of Date

### ISSUE THREAD

**Issue by gewthen** [sionescu/bordeaux-threads#53]
The official documentation listed in README.md is significantly out of date. It ismissing various new features of bordeaux-threads, such as semaphores, locks, timesout...etc.

**Comment by phoe** [comment]
Would it be beneficial to make the documentation automatically buildable based on the state of the repository (e.g. via Travis CI and deployed on GitHub Pages) and put the link to the new page on the current trac wikipage?

If yes, I can attempt to perform that feat. BT documentation has been out of date for a very, very long time.

**Comment by sionescu** [comment]
Hi @phoe, it would very much welcome a PR to that effect.

**Comment by phoe** [comment]
@sionescu OK, I will attempt to do that on my own fork. I'll likely need some help setting up Travis for this repository once I have something that works.

**Comment by phoe** [comment]
(Also, if you feel like it, you can assign me to this GitHub issue, so I am less likely to forget about it.)

**Comment by sionescu** [comment]
Done. Also, try to look into using Github Actions instead. Given that the latter have also Windows and OSX, I'd like to test B-T on more OSes.

**Comment by phoe** [comment]
> Given that the latter have also Windows and OSX

So does Travis - I have been building/testing Lisp stuff for Win/Mac/Linux for a while now using Travis.

Still, you're the boss here; I have no problem with learning GitHub actions instead if that's your preference.

**Comment by phoe** [comment]
I plan on using https://github.com/Shinmera/staple/ for the generated docfile(s). Is that choice okay with you?

**Comment by sionescu** [comment]
Since we already use Travis, let's stick with that.
For the doc generator, as long as it's possible to write the docs manually, with no code involved I'm fine. Staple seems to have a Markdown plugin, so that should be ok.

**Comment by phoe** [comment]
Yes, it seems so. Staple generates documentation for individual symbols based on the state of the package system after it loads an ASDF system, but it allows arbitrary text to be stored in the generated documentation, e.g. via its Markdown plugin.

**Comment by sionescu** [comment]
What I meant is that I don't want any auto-generated contents at all, just a Markdown engine with some default CSS.

**Comment by digikar99** [comment]
Does [mkdocs](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes) work?

Also, may be [this](https://github.com/digikar99/common-lisp.readthedocs/blob/master/docs/bordeaux-threads.md) works as a starting point - I've merely extracted the docstrings - not sure if I missed something. As for arranging things into sections, my personal preference is to make section-wise symbol lists at the beginning of the doc - something like [this](https://digikar99.github.io/common-lisp.readthedocs/postmodern/#connecting-to-the-postgres-server) - and letting symbols stay in alphabetical order; not sure if that's better than what currently is.

**Comment by mdbergmann** [comment]
> I plan on using https://github.com/Shinmera/staple/ for the generated docfile(s). Is that choice okay with you?

Staple unfortunately has an awful default CSS and no 'sidebar'.
From a visual point of view I like https://github.com/CommonDoc/codex much better.
Staple should be 'fixed' with a proper nicely styled CSS.

**Comment by sionescu** [comment]
I decided to use Hugo in the end, with the [techdoc theme](https://themes.gohugo.io/hugo-theme-techdoc/). You can see a preview [here](https://capella.cddr.org/bordeaux-threads/).

**Comment by mdbergmann** [comment]
How does it work? Do you write it by hand?

**Comment by sionescu** [comment]
Yes. It's a bit tedious to write all that, including the xrefs to the Hyperspec, but I don't expect it to change often once it's done.

**Comment by mdbergmann** [comment]
I'm struggling a bit to figure out how the new API (v2) is to be used?
Is automatically used with a recent (0.8.8) version of BT from Quicklisp? Or is there a different dependency declaration needed?

**Comment by phoe** [comment]
You need to explicitly use the `bordeaux-threads-2` package, as per https://github.com/sionescu/bordeaux-threads/blob/master/apiv2/pkgdcl.lisp#L4

**Comment by sionescu** [comment]
You need to use HEAD because I haven't released it yet, and switch to the symbols in package `bordeaux-threads-2` or `bt2`.

**Comment by sionescu** [comment]
Closing because I've updated the documentation.
