### ISSUE TITLE
Semaphores on Mac

### ISSUE THREAD

**Issue by chuchana** [sionescu/bordeaux-threads#56]
Is it possible that semaphores are not supported on Mac OS X? I had a problem loading log4cl because of them and when I load just bordeaux-threads, I cannot jump to their definitions. No problems on Arch Linux.

**Comment by chuchana** [comment]
It looks like POSIX are not completely implemented on the system level. E.g. `sem_timedwait()` [[1]](https://stackoverflow.com/questions/641126/posix-semaphores-on-mac-os-x-sem-timedwait-alternative), and named semaphores [[2]](https://heldercorreia.com/semaphores-in-mac-os-x-fd7a7418e13b). Assuming that information is still up to date, but at least for `sem_timedwait`, I've seen that problem not too long ago.

**Comment by scymtym** [comment]
@chuchana Please state with which CL implementation (including the version) and on which architecture (e.g. x86, x86_64, arm64, etc.) you encountered this problem and what one has to do to reproduce it.

Please also double-check the bordeaux-threads version, for example using `(asdf:component-version (asdf:find-system :bordeaux-threads))`.

**Comment by chuchana** [comment]
@scymtym Thank you, `(asdf:component-version (asdf:find-system :bordeaux-threads))` helped me find the problem: it was version 0.8.4, which was neither in the quicklisp dist directory, nor in my local projects. `(asdf:component-pathname (asdf:find-system :bordeaux-threads))` revealed that it was inside a subdirectory of some other project I had cloned into the local projects directory years ago. Removing it solved the problem.
