### ISSUE TITLE
clasp-integration not visible in quicklisp

### ISSUE THREAD

**Issue by kpoeck** [sionescu/bordeaux-threads#58]
this is for sure since the quicklisp library definition in 
https://github.com/quicklisp/quicklisp-projects/blob/master/projects/bordeaux-threads/source.txt
says:
`latest-github-release https://github.com/sionescu/bordeaux-threads.git`

and the latest release is Version 0.8.6 which does not contain the clasp integration yet.

i assume the easiest fix would be to make a new release of bordeaux-threads but any other method that achieves the same goal is also welcome.

**Comment by kpoeck** [comment]
New release was done, so I assume the issue is solved with the next quicklisp release

**Comment by sionescu** [comment]
Yes, that's correct.
