### ISSUE TITLE
The test for condition-wait (test condition-variable) is not good

### ISSUE THREAD

**Issue by Yehouda** [sionescu/bordeaux-threads#65]
1) The test for condition-wait (test condition-variable)  can hang if the thread awoke in a difference order than the order they are made. For example, assume threads 1 and 2 start waiting before before thread 0 did notify. When thread 0 notify, thread 2 wake up, see that *shared* is 1, and goes waiting again. Now all the other threads and main thread hang. 

Playing with this, as far as I can tell it works most of the cases because none of the threads waits. They all go in the right order through getting the lock (*lock*), so by the time each one of them gets the lock, *shared* is already the right number. Even if some of the threads are out of order, some of the "spare" calls to condition-notify form earlier threads that didn't wait may be delayed enough to re-start the chain again, but not always. 

Also the main thread gets hung in this case. Really it should not depend on conditions, for example do something like:
 (dotimes (x 100) (sleep 0.05) (when  (= num-procs *shared*) (return))
so ensure that that the test doesn't hang even if condition-wait is broken.  SHould do something to get rid of the threads in this case. 

2) The test for old implementations of condition on LispWorks (before 6.0) need to be conditionalized  the same way that "impl-lispworks-condition-variables" is conditionalized in the asd file, because it relies on code from this file.

**Comment by sionescu** [comment]
I'd be grateful if you could propose a fix because I don't have a LW licence so I can't test.

**Comment by Yehouda** [comment]
I think that test the basics. 

It doesn't test what happens when several processes notify at the same time. 

[condition-varaible-a.txt](https://github.com/sionescu/bordeaux-threads/files/4580443/condition-varaible-a.txt)

**Comment by sionescu** [comment]
Hi @Yehouda, by fix I meant a pull request.

**Comment by Yehouda** [comment]
I don't actually work in github at all. I download using quicklisp and test that.
