### ISSUE TITLE
BT on Clisp PPC G5

### ISSUE THREAD

**Issue by mdbergmann** [sionescu/bordeaux-threads#66]
Hi.

I'm not sure if this is actually supposed to work.

I have revived my old PowerMac G5. The only lisp available is Clisp.
Quicklisp, after installing asdf 3 manually works OK.

My project I'm working on uses lparallel which is based on bordeaux-threads.

Creating a kernel with 1 thread results in the following stack trac, see attached picture.

For any hint of what's going wrong I'd be greatful.
![Bildschirmfoto vom 2020-03-06 21-07-05](https://user-images.githubusercontent.com/2143978/76119262-5a98b080-5fef-11ea-9b85-dcb8a2a9b484.png)

Manfred

**Comment by sionescu** [comment]
What's the operating system, OSX ? Have you tried using CCL ?

**Comment by mdbergmann** [comment]
No, it's a Debian based PPC Linux (Mint).

**Comment by sionescu** [comment]
You might have problems finding a CL implementation that supports threads. Maybe SBCL ? See http://sbcl.org/platform-table.html

**Comment by mdbergmann** [comment]
OK, so it's the CLisp that doesn't work?

**Comment by sionescu** [comment]
From the error message, it looks like Clisp wasn't compiled with threads support.

**Comment by mdbergmann** [comment]
Alright. I'll check if I can compile or get an older SBCL.
Thanks for checking.
