### ISSUE TITLE
WITH-LOCK-HELD + BREAK = released locks?

### ISSUE THREAD

**Issue by phoe** [sionescu/bordeaux-threads#68]
https://trac.common-lisp.net/bordeaux-threads/wiki/ApiDocumentation states on `with-lock-held`:

> Note that if the debugger is entered, it is unspecified whether the lock is released at debugger entry or at debugger exit when execution is restarted.

Does it mean that calling `break` (which itself calls `invoke-debugger`) inside the body of `with-lock-held` code may cause the holding thread to release all locks that it holds? This passage is particularly confusing for me.

**Comment by sionescu** [comment]
That sounds like a remnant from before the time of SMP threads, but I'm not sure it's correct.

**Comment by sionescu** [comment]
Closing because I've updated the documentation.
