### ISSUE TITLE
Expose condition-var in defpackage?

### ISSUE THREAD

**Issue by eviltofu** [sionescu/bordeaux-threads#74]
Should the `condition-var` struct be exposed in defpackage? When I try to define a slot `:type` in a class as `bt:condition-var` I get a `The symbol "CONDITION-VAR" is not external in the BORDEAUX-THREADS package.` error.

**Comment by sionescu** [comment]
The API version 2 will export a "CONDITION-VARIABLE" type. You can have a preview in the "apiv2" branch, which I will merge soon.
