### ISSUE TITLE
In apiv2 package bordeaux-threads-2,  the "or" forms in atomic-incf and atomic-decf are not correct

### ISSUE THREAD

**Issue by DCarnikalis** [sionescu/bordeaux-threads#78]
In file "_apiv2/atomics.lisp_" in apiv2 package <code>**:bordeaux-threads-2**</code>, the two <code>**or**</code> forms within the two macros <code>**atomic-incf**</code> and <code>**atomic-decf**</code> are each missing <code>**lispworks**</code>.

**Comment by sionescu** [comment]
Thanks.
