### ISSUE TITLE
Weird dead-lock with apiv2 when using log4cl :debug logging

### ISSUE THREAD

**Issue by mdbergmann** [sionescu/bordeaux-threads#80]
Hi.

I'm not sure if this is anywhere remotely connected, but maybe it is.

I've tried switching my project over to `bt2`.
With a log level of `:warn`, or `:info` seems to work fine.
However, when I switch to log level `:debug`, which produces quite a bit of more log, I'm seeing dead-locks.

Could it be, while within the same image and log4cl uses apiv1 and my code uses apiv2 that there could be issues?

Manfred

**Comment by sionescu** [comment]
I don't know, it would be helpful if you could come up with a reduced test case. I don't have a lot of free time to debug this.

**Comment by mdbergmann** [comment]
Yeah, not so simple. But I'll try.

**Comment by sionescu** [comment]
Any news on this ?

**Comment by mdbergmann** [comment]
I will have a look if it is still the case with apiv2.

**Comment by mdbergmann** [comment]
Couldn't reproduce anymore.
