### ISSUE TITLE
Inconsistent behaviour between ACL and SBCL

### ISSUE THREAD

**Issue by luismbo** [sionescu/bordeaux-threads#81]
```lisp
(let ((thread (bt:make-thread (lambda ()))))
  (bt:join-thread thread)
  (bt:destroy-thread thread))
```

signals an error on SBCL (`Interrupt thread failed: thread #<THREAD "Anonymous thread" FINISHED values: NIL {102AC2BF83}> has exited.`) but not ACL.

I'm inclined to vote for ACL's behaviour since there's no good way to reliably ensure that the thread hasn't yet exited before destroying it.

**Comment by sionescu** [comment]
This one is hard to fix though if the implementation doesn't support it. I'll have to think about it.

**Comment by sionescu** [comment]
How about these semantics: a thread is in an unknown state, but `join-thread` and `destroy-thread` observe its state and collapse its wave function so to speak. The first invocation of one of these functions should always succeed regardless of whether the thread has already terminated or not. A second invocation should always signal an error. Does that sound reasonable ?

Specifically, in this case a `destroy-thread` following a `join-thread` should always signal an erorr regardless of implementation.

**Comment by luismbo** [comment]
The only drawback there would be if one, for some reason, wanted to wait for the same thread from multiple other threads (I've never come across this) but POSIX says `The results of multiple simultaneous calls to pthread_join() specifying the same target thread are undefined.` so your proposal seems reasonable, though it might not particularly help with this undefined behavior unless you plan to use a mutex in `join-thread`.

In any case, the wave function analogy is neat. 🤓

**Comment by sionescu** [comment]
I fixed this in APIv2, by checking whether the thread is alive when destroying. There's still a short race condition window, where a thread might be alive when checking but have exited an epsilon later, just before being destroyed, but I think it's good enough for the moment.
