### ISSUE TITLE
Wrap timeout conditions to always be 'bt:timeout

### ISSUE THREAD

**Issue by mdbergmann** [sionescu/bordeaux-threads#84]
Currently, SBCL will raise `'sb-ext:timeout`, ccl, ecl: `'bt:timeout`.
This depends on whether there is a native variant of `with-timeout`.
All uses of `with-timeout` should catch native timeout and repackage as `'bt:timeout`, maybe add 'cause' slot to `'bt:timeout` which can hold the native timeout condition.

**Comment by sionescu** [comment]
Are you referring to APIv1 or APIv2 ?

**Comment by mdbergmann** [comment]
Both.

This should in fact be relatively simple to do. Basically just a `handle-case` on top of each implementations `with-timeout`.
I can have a look at it and make a PR.

**Comment by sionescu** [comment]
> Both.


> This should in fact be relatively simple to do. Basically just a `handle-case` on top of each implementations `with-timeout`.
> I can have a look at it and make a PR.


You don't need to handle the condition, just add a type alias. That becomes a bit more difficult if the with-timeout implementation doesn't signal a specific condition type, but only a SIMPLE-ERROR or such.

--
Stelian Ionescu

**Comment by informatimago** [comment]
> Both.
> 
> This should in fact be relatively simple to do. Basically just a `handle-case` on top of each implementations `with-timeout`.
> I can have a look at it and make a PR.

Don't wrap handlers, just rename the bt::interrupt condition as bt:timeout condition.

**Comment by informatimago** [comment]
> Are you referring to APIv1 or APIv2 ?

How do we know?  I see that in bordeaux-threads-v0.8.8 from quicklisp.

**Comment by informatimago** [comment]
> Both. This should in fact be relatively simple to do. Basically just a `handle-case` on top of each implementations `with-timeout`. I can have a look at it and make a PR.
> You don't need to handle the condition, just add a type alias. That becomes a bit more difficult if the with-timeout implementation doesn't signal a specific condition type, but only a SIMPLE-ERROR or such.

Indeed, assuming we have an implementation specific with-timeout that does that.  But for implementations that defer to the default implementation that uses process-interrupt to signal the condition, we can just signal a bt:timeout condition, https://github.com/sionescu/bordeaux-threads/blob/69f979d669c4bdebc506bf559e1e342b0fbb3c9a/apiv1/bordeaux-threads.lisp#L73

**Comment by sionescu** [comment]
@mdbergmann can you provide a test case that shows what the problem is exactly ?

**Comment by mdbergmann** [comment]
Hi.

I need to have this in my code to make sure to wrap a bt:timeout or sb-ext:timeout when run on SBCL:

```lisp
(defmacro with-waitfor ((wait-time) &body body)
  (with-gensyms (c)
    `(handler-case
         (bt:with-timeout (,wait-time)
                     ,@body)
       (bt:timeout (,c)
         (error ,c))
       #+sbcl
       (sb-ext:timeout (,c)
         (log:warn "sb-ext:timeout, wrapping to 'expired'.")
         (error 'bt:timeout :length ,wait-time)))))
```

I would assume that there should not be a special case necessary for SBCL.

**Comment by sionescu** [comment]
Are you seeing this behaviour on the latest release ? Using BT HEAD on SBCL 2.1.0 this doesn't reproduce.

**Comment by sionescu** [comment]
For example: (typep (make-condition 'sb-ext:timeout) 'bt:timeout) => T

**Comment by sionescu** [comment]
Furthermore, there is a test that covers this (`with-timeout-signals`), and it passes in the CI environment.

**Comment by mdbergmann** [comment]
Seems good with SBCL >= 2.1.0
