### ISSUE TITLE
Main ASDF file fails to load in LW 7.x

### ISSUE THREAD

**Issue by marcoxa** [sionescu/bordeaux-threads#88]
Hi

The very first line of the main ASDF bombs on LW.

```
#.(unless (or #+asdf3.1 (version<= "3.1" (asdf-version)))
    (error "You need ASDF >= 3.1 to load this system correctly."))
```

The error is caused by the missing `VERSION<=`.  I do have `:asdf3.1` (and 3.2, and 3.3) in my `*features*`.

Cheers

MA

**Comment by marcoxa** [comment]
Ok.  Found out why.  The main ASDF file assumes that the ASDF and UIOP packages are already "used".

It may not be so.

Easy fix: put all the package qualifiers in place, including the `asdf:test-op`.

**Comment by sionescu** [comment]
A .asd file is not a general Lisp file and cannot be loaded by CL:LOAD because ASDF needs to setup a special environment for everything to work. When changing a .asd I usually just reload the whole system, which ensures that ASDF will read the .asd correctly.

**Comment by sionescu** [comment]
The correct loader for .asd files is asdf:load-asd.

**Comment by marcoxa** [comment]
Maybe.

But that breaks the workflow people may have.  Like "Use the GUI to load a file".

The fix avoids this problem.

Cheers

MA

**Comment by sionescu** [comment]
This was broken long ago. Please ask Lispworks to fix their GUI: when the extension is "asd" use asdf:load-asd.

**Comment by sionescu** [comment]
Slime already does that when the swank-asdf contrib is loaded.

**Comment by marcoxa** [comment]
It is much easier and friendlier to fix the ASD file.

**Comment by sionescu** [comment]
ASD files are not general Lisp files and the editor must take that into account. The friendliness that you see means just a brokenness that might or might not be obvious to the user, and which don't want to commit to maintaining.

**Comment by marcoxa** [comment]
I am sorry but that is your opinion.

IMHO it is the BT ASD file that is "broken".

The fix is easy and it would make no difference to the BT users.

**Comment by sionescu** [comment]
It is not my opinion. It is a fact.

**Comment by marcoxa** [comment]
Ok.  What the other maintainers think?

**Comment by marcoxa** [comment]
WTF.  Stelian.  Closing this issue is really rude.

**Comment by sionescu** [comment]
I'm the only maintainer. Calling it only "my opinion" is rude too. Conversation closed.
