### ISSUE TITLE
compile error on SBCL 1.4.16.debian @ Linux 5.4.83+ armv6l

### ISSUE THREAD

**Issue by VaclavSynacek** [sionescu/bordeaux-threads#91]
Hello,
I am trying to use the 20210302003708 ultralisp version.
It compiles nicely on SBCL 2.1.1.debian @ Linux 5.10.0-4-amd64 x86_64
but fails to compile on SBCL 1.4.16.debian @ Linux 5.4.83+ armv6l (current version on raspbian on raspberry pi).

Error output with only username redacted:
```
; Loading "bordeaux-threads"
[package global-vars].............................
[package trivial-garbage].........................
[package bordeaux-threads]........................
[package bordeaux-threads-2]...
; file: ~/quicklisp/dists/ultralisp/software/sionescu-bordeaux-threads-20210302003708/apiv2/atomics.lisp
; in: DEFUN ATOMIC-INTEGER-CAS
;     (BORDEAUX-THREADS-2::ATOMIC-CAS
;      (BORDEAUX-THREADS-2::ATOMIC-INTEGER-CELL BORDEAUX-THREADS-2::ATOMIC-INTEGER)
;      BORDEAUX-THREADS-2::OLD BORDEAUX-THREADS-2::NEW)
; --> LET EQL IF EQL COMPARE-AND-SWAP 
; ==>
;   (CAS
;    (BORDEAUX-THREADS-2::ATOMIC-INTEGER-CELL BORDEAUX-THREADS-2::ATOMIC-INTEGER)
;    BORDEAUX-THREADS-2::OLD BORDEAUX-THREADS-2::NEW)
; 
; caught ERROR:
;   during macroexpansion of
;   (SB-EXT:CAS (ATOMIC-INTEGER-CELL ATOMIC-INTEGER) OLD ...). Use
;   *BREAK-ON-SIGNALS* to intercept.
;   
;    Cannot use COMPARE-AND-SWAP with structure accessor for a typed slot: (ATOMIC-INTEGER-CELL
;                                                                           ATOMIC-INTEGER)
```

**Comment by VaclavSynacek** [comment]
Sorry about this. It is probably caused by the old sbcl. I had the same problem with ecl on the two machines. After building new ecl on the raspberry pi, it started working. I will also compile new sbcl (it takes hours on the pi), but judging from ecl, I suspect this is not a problem with current version of bt or the different architecture, but rather only that current bt does not compile on obsolete versions of cl implementations, which is to be expected I guess.

**Comment by sionescu** [comment]
Hi Vaclav, I usually try to keep compatibility with implementations a couple of years old but not more than that. Happy this got solved.
