### ISSUE TITLE
with-lock-held and condition-wait

### ISSUE THREAD

**Issue by avodonosov** [sionescu/bordeaux-threads#95]
The `condition-wait`, both in apiv1 apiv2, can return `nil` meaning that the lock is not held anymore:

https://github.com/sionescu/bordeaux-threads/blob/552fd4dc7490a2f05ed74123f4096fb991673ac0/apiv1/default-implementations.lisp#L243

https://github.com/sionescu/bordeaux-threads/blob/552fd4dc7490a2f05ed74123f4096fb991673ac0/apiv2/api-condition-variables.lisp#L70

Does it mean the following pattern is incorrect?

```common-lisp
(with-lock-held (lock)
  ;...
  (condition-wait cond-var lock :timeout n)
  ;...)

```

**Comment by avodonosov** [comment]
If the NIL can only be returned on SBCL, then the `with-lock-held` / `condition-wait` coding pattern works fine even on API v1, which on SBCL just delegates `with-lock-held` to `sb-thread:with-mutex` and  `condition-notify` to `sb-thread:condition-notify`.

The `sb-thread:condition-notify` docstring provides an example of using it inside of `sb-thread:with-mutex` 
https://github.com/sbcl/sbcl/blob/19a2d5c8d2d2c2a92762ef9a7d15c6daa855bc46/src/code/target-thread.lisp#L1100.

This works because `sb-thread:release-mutex` by default just does nothing if the current thread is not owner of the mutex:
https://github.com/sbcl/sbcl/blob/19a2d5c8d2d2c2a92762ef9a7d15c6daa855bc46/src/code/target-thread.lisp#L882

**Comment by avodonosov** [comment]
@sionescu , in this case it can probably be good to update `condition-wait` docstring in the API v1 with a note that it is safe to use within the `with-lock`. And on the API v2, where you've added re-acquisition of  the lock, change the docstring to say that "always retrun T (for historical reason)" and that "the thread will wait till another thread notified it using CONDITION-NOTIFY, timeout elapsed, or suprious-wake up happened. The thread then waits to re-acquire the LOCK". 

BTW, I now realized that SBCL's approach is most likely motivated by desire to not exceed the timeout when trying to re-acquire the lock.

**Comment by sionescu** [comment]
I changed the docstrings to clarify the semantics of the return value. I also noticed (sorry for the confusion), that I had already changed SBCL's condition-wait to re-acquire the lock on timeout, two years ago in aa1bf8e2f2de067790f1154c82b919b182bc6c61. I added a test for that, and fixed ECL too.
